---
- name: "Use the latest packages"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - nginx
  notify: "Restart nginx"
  tags: "nginx"

- name: "Start at boot"
  service:
    name: "{{ item }}"
    state: "started"
    enabled: yes
  with_items:
    - nginx
  tags: "nginx"

- name: "Configure /etc/nginx/nginx.conf"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart nginx"
  tags: "nginx"

